export type a1_T<Val> = [Val]
export type a2_T<Val> = [...a1_T<Val>, Val]
export type a3_T<Val> = [...a2_T<Val>, Val]
export type a4_T<Val> = [...a3_T<Val>, Val]
export type a5_T<Val> = [...a4_T<Val>, Val]
export type a6_T<Val> = [...a5_T<Val>, Val]
export type a7_T<Val> = [...a6_T<Val>, Val]
export type a8_T<Val> = [...a7_T<Val>, Val]
export type a9_T<Val> = [...a8_T<Val>, Val]
export type a10_T<Val> = [...a9_T<Val>, Val]
export type a20_T<Val> = [...a10_T<Val>, ...a10_T<Val>]
export type a30_T<Val> = [...a20_T<Val>, ...a10_T<Val>]
export type a40_T<Val> = [...a30_T<Val>, ...a10_T<Val>]
export type a50_T<Val> = [...a40_T<Val>, ...a10_T<Val>]
export type a100_T<Val> = [...a50_T<Val>, ...a50_T<Val>]
export type a200_T<Val> = [...a100_T<Val>, ...a100_T<Val>]
export type a300_T<Val> = [...a200_T<Val>, ...a100_T<Val>]
export type a400_T<Val> = [...a300_T<Val>, ...a100_T<Val>]
export type a500_T<Val> = [...a400_T<Val>, ...a100_T<Val>]
export type a1000_T<Val> = [...a500_T<Val>, ...a500_T<Val>]
export type a_1_T<A extends any[]> = A
export type a_2_T<A extends any[]> = a_1_T<A>
export type a_3_T<A extends any[]> = a_2_T<A>
export type a_4_T<A extends any[]> = a_3_T<A>
export type a_5_T<A extends any[]> = a_4_T<A>
export type a_6_T<A extends any[]> = a_5_T<A>
export type a_7_T<A extends any[]> = a_6_T<A>
export type a_8_T<A extends any[]> = a_7_T<A>
export type a_9_T<A extends any[]> = a_8_T<A>
export type a_10_T<A extends any[]> = a_9_T<A>
export type a_20_T<A extends any[]> = a_10_T<a_10_T<A>>
export type a_30_T<A extends any[]> = a_20_T<a_10_T<A>>
export type a_40_T<A extends any[]> = a_30_T<a_10_T<A>>
export type a_50_T<A extends any[]> = a_40_T<a_10_T<A>>
export type a_100_T<A extends any[]> = a_50_T<a_50_T<A>>
export type a_200_T<A extends any[]> = a_100_T<a_100_T<A>>
export type a_300_T<A extends any[]> = a_200_T<a_100_T<A>>
export type a_400_T<A extends any[]> = a_300_T<a_100_T<A>>
export type a_500_T<A extends any[]> = a_400_T<a_100_T<A>>
export type a_1000_T<A extends any[]> = a_500_T<a_500_T<A>>
